# Generated by Django 4.2.18 on 2025-05-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sign",
            fields=[
                ("username", models.CharField(max_length=200, unique=True)),
                ("email", models.EmailField(max_length=200, unique=True)),
                (
                    "userid",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=200)),
            ],
        ),
    ]
